### ISSUE TITLE
Assembly table suggestion: Use ingredients after item is crafted

### ISSUE THREAD

**Issue by Ithronyar** [SanAndreasP/TurretModRebirth#16]
Small suggestion that will prevent items being deleted from the assembly table. Right now, the assembly table removes ingredients from its inventory, _then_ crafts an item. Which means if you want to cancel the item, your ingredients have already been destroyed and you won't get them back. This makes the cancel button an essentially useless troll feature, since you've already lost your items _and_ you don't get your turret/upgrade/whatever.

**Comment by SanAndreaP** [comment]
The mechanic was inspired by EnderIO. Also due to performance reasons, as it doesn't have to re-check the inventory every tick if the ingredients are still valid.
I'll change it to still use ingredients before the table crafts, but give items back if crafting operation is canceled / table is destroyed. That should be a good compromise.
