### ISSUE TITLE
Right clicking turrets with TCU crashes the game

### ISSUE THREAD

**Issue by UEMxMDE** [SanAndreasP/TurretModRebirth#30]
[ Please replace text in [] with the answer from the above question! ]

Do you use Java 8?
Yes

What version of Minecraft do you use?
1.12.2

What version of MinecraftForge do you use?
14.23.5.2860

What version of SanLib do you use?
SanLib-1.12.2-1.6.3

What version of Turret Mod Rebirth do you use?
TurretMod-1.12-4.0.0-beta.4.6
 
What is the issue / bug you have encountered? Give us a short description.
Right clicking a turret with the Turret Control Unit crashes the game.

How can it be reproduced?
Right click a placed turret with a Turret Control Unit

Please post your log file (either in /logs/fml-client-latest.log or /logs/latest.log) on https://gist.github.com and provide the link:
I have replaced my in-game username in the logs with "---"
https://gist.github.com/UEMxMDE/4f2d23ae406045040b947086cd4dfd06

This message shows up in the Minecraft launcher after Minecraft crashes:
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error
Exit Code: -1

**Comment by captinalex1** [comment]
Been having that same odd bug and have been trying to search through the different configs and can't find a fix. It doesn't happen consistently either, it's actually pretty random and happens because of the little skull in the TCU, mod runs with no issues if you don't use the TCU. I dont know of any workarounds, maybe you might San?
 
https://gist.github.com/captinalex1/85adfe50fed848d066ec3fe77ec1cd5c

**Comment by captinalex1** [comment]
I know I'm using an older version, but that's because it happens way less in the older version. Beta 4.6 UEMxMDE is using it happens constantly from my testing. I'm not very good with code but if you removed the little skull at the bottom in the TCU, would that clear the bug? Or is the TCU trying to locate a skull that doesn't exist? I'm just throwing ideas your way. Wanna help the best I can.

**Comment by alexva12** [comment]
Hey there, madhaus pack dev here. I'm having the same exact issue with my modpack. constantly crashes when right clicking with the TCU. When I had beta 3 in my pack, everything worked completely fine. everyone experiencing this issue should try using beta 3. As per what captianalex was saying in the above post, at least until this hopefully gets resolved for those of us that still use 1.12.2

**Comment by SanAndreaP** [comment]
Just cleaning up :)
The 1.12.2 version is not maintained anymore and the current iteration for 1.16 (unreleased, as of writing this) has this problem fixed.
